apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keepalive
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: keepalive
    spec:
      containers:
        - name: "keepalive"
          imagePullPolicy: "Always"
          image: "lsstsqre/nfsclienttest"
          # Use this for manual testing.
          #securityContext:
          #  privileged: true
          volumeMounts:
            - name: home
              mountPath: /home
            - name: scratch
              mountPath: /scratch
            - name: project
              mountPath: /project
            - name: datasets
              mountPath: /datasets
              readOnly: true
            - name: software
              mountPath: /software
              readOnly: true
            - name: teststand              
              mountPath: /lsstdata/offline/teststand
              readOnly: true              
      volumes:
        - name: home
          nfs:
            server: {{NFS_SERVER_IP_ADDRESS}}
            path: /exports/home
        - name: scratch
          nfs:
            server: {{NFS_SERVER_IP_ADDRESS}}
            path: /exports/scratch
        - name: project
          nfs:
            server: {{NFS_SERVER_IP_ADDRESS}}
            path: /exports/project
        - name: datasets
          nfs:
            server: {{NFS_SERVER_IP_ADDRESS}}
            path: /exports/datasets
            readOnly: true            
        - name: software
          nfs:
            server: {{NFS_SERVER_IP_ADDRESS}}
            path: /exports/software
            readOnly: true            
        - name: teststand
          nfs:
            server: {{NFS_SERVER_IP_ADDRESS}}
            path: /exports/teststand
            readOnly: true
          
