kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prepuller
subjects:
- kind: ServiceAccount
  name: prepuller
  namespace: {{CLUSTER_IDENTIFIER}}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: prepuller
  apiGroup: ""

