kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{CLUSTER_IDENTIFIER}}
  name: prepuller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "update", "delete"]
