apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prepuller
spec:
  template:
    metadata:
      labels:
        name: prepuller
    spec:
      containers:
        - name: prepuller
          imagePullPolicy: "Always"
          image: "lsstsqre/prepuller"
          securityContext:
            privileged: true
          # env:
          # Both of these should be comma-separated lists
          #  - name: LAB_CONTAINER_NAMES
          #    value: <set if you don't want to just get most recent
          #            builds>
          #  - name: JLD_INFRASTRUCTURE_IMAGES
          #    value: defaults to "lsstsqre/jld-hub"
          volumeMounts:
            - name: dockerdir
              mountPath: /var/run/docker
            - name: dockersock
              mountPath: /var/run/docker.sock
            - name: dockershim
              mountPath: /var/run/dockershim.sock
            - name: dockerpid
              mountPath: /var/run/docker.pid
            - name: dockerbin
              mountPath: /usr/bin/docker
            - name: dockerlib
              mountPath: /var/lib/docker
              # You may need to vary these depending on the host system.
              #  Basically, run `ldd /usr/bin/docker` and capture the
              #  locations of the libraries you will need to link.
            - name: libapparmor
              mountPath: /usr/lib64/libapparmor.so
            - name: libapparmor1
              mountPath: /usr/lib64/libapparmor.so.1
            - name: libapparmor130
              mountPath: /usr/lib64/libapparmor.so.1.3.0
            - name: libseccomp
              mountPath: /usr/lib64/libseccomp.so
            - name: libseccomp2
              mountPath: /usr/lib64/libseccomp.so.2
            - name: libseccomp231
              mountPath: /usr/lib64/libseccomp.so.2.3.1
            # - name: libltdl7
            #   mountPath: /usr/lib64/libltdl.so.7
      volumes:
        - name: dockerdir
          hostPath:
            path: /var/run/docker
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: dockershim
          hostPath:
            path: /var/run/dockershim.sock
        - name: dockerpid
          hostPath:
            path: /var/run/docker.pid
        - name: dockerbin
          hostPath:
            path: /usr/bin/docker
        - name: dockerlib
          hostPath:
            path: /var/lib/docker
        - name: libapparmor
          hostPath:
            path: /usr/lib64/libapparmor.so
        - name: libapparmor1
          hostPath:
            path: /usr/lib64/libapparmor.so.1
        - name: libapparmor130
          hostPath:
            path: /usr/lib64/libapparmor.so.1.3.0
        - name: libseccomp
          hostPath:
            path: /usr/lib64/libseccomp.so
        - name: libseccomp2
          hostPath:
            path: /usr/lib64/libseccomp.so.2
        - name: libseccomp231
          hostPath:
            path: /usr/lib64/libseccomp.so.2.3.1
        # - name: libltdl7
        #   hostPath:
        #     path: /usr/lib64/libltdl.so.7
