kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: physpvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{PHYSICAL_SHARED_VOLUME_SIZE}}
  storageClassName: fast

