apiVersion: apps/v1
kind: Deployment
metadata:
  name: js9
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: js9
    spec:
      containers:
        - name: js9
          imagePullPolicy: "Always"
          image: "lsstsqre/js9server"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: HTTP_PORT
              value: '8080'
            - name: HTTP_CONTENT_DIR
              value: '/www'
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
