apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: firefly
spec:
  replicas: {{FIREFLY_REPLICAS}}
  template:
    metadata:
      labels:
        name: firefly
    spec:
      containers:
        - name: "firefly"
          imagePullPolicy: "Always"
          image: "ipac/firefly:lsst-dev"
          securityContext:
            runAsUser: {{FIREFLY_UID}}
          volumeMounts:
            - name: jld-fileserver-scratch
              mountPath: /scratch
          resources:
            limits:
              memory: {{FIREFLY_CONTAINER_MEM_LIMIT}}
              cpu: {{FIREFLY_CONTAINER_CPU_LIMIT}}
            requests:
              memory: 3G
              cpu: 0.8
          env:
            - name: MANAGER
              value: 'FALSE'
            - name: FIREFLY_OPTS
              value: "-Dvisualize.fits.search.path=/scratch/firefly"
            - name: FIREFLY_SHARED_WORK_DIR
              value: "/scratch/firefly/workarea"
            - name: MAX_JVM_SIZE
              value: {{FIREFLY_MAX_JVM_SIZE}}
            - name: DEBUG
              value: 'false'
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firefly
                  key: admin.password              
      volumes:
        - name: jld-fileserver-scratch
          persistentVolumeClaim:
             claimName: jld-fileserver-scratch
