kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub
rules:
- apiGroups: [""]
  resources: ["pods","events", "namespaces", "serviceaccounts", "services",
  "persistentvolumeclaims", "persistentvolumes", "resourcequotas"]
  verbs: ["get", "list", "create", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "create", "watch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "delete"]
