apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jld-hub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jld-hub
    spec:
      containers:
        - name: jld-hub
          imagePullPolicy: "Always"
          image: "lsstsqre/jld-hub"
          ports:
            -
              containerPort: 8000
              name: jld-hub
          env:
            - name: LOGLEVEL
              value: INFO
            - name: LAB_CONTAINER_NAMES
              value: 'lsstsqre/jld-lab-py2:latest,lsstsqre/jld-lab-py3:latest'
            - name: LAB_CONTAINER_DESCS
              value: 'LSST Stack (Python 2),LSST Stack (Python 3)'
            - name: LAB_SELECTOR_TITLE
              value: 'LSST Stack Selector'
            # - name: LAB_MEM_LIMIT
            #   value: '2G'
            # - name: LAB_CPU_LIMIT
            #   value: '1'
            # - name: LAB_MEM_GUARANTEE
            #   value: '0K'
            # - name: LAB_CPU_GUARANTEE
            #   value: '0'
            - name: GITHUB_ORGANIZATION_WHITELIST
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: github_organization_whitelist
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: github_client_id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: github_secret
            - name: OAUTH_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: github_oauth_callback_url
            - name: SESSION_DB_URL
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: session_db_url
          # If you use sqlite, you want this to persist sessions across
          #  jupyterhub restarts.
          volumeMounts:
            - name: jld-fileserver-home
              mountPath: /home
      volumes:
        - name: jld-fileserver-home
          persistentVolumeClaim:
             claimName: jld-fileserver-home
