apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jld-hub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jld-hub
    spec:
      containers:
        - name: jld-hub
          imagePullPolicy: "Always"
          image: "lsstsqre/jld-hub"
          ports:
            -
              containerPort: 8000
              name: jld-hub
          env:
            - name: LOGLEVEL
              value: INFO
            - name: LAB_CONTAINER_NAMES
              value: 'lsstsqre/jld-lab-w201726,lsstsqre/jld-lab-w201725,lsstsqre/jld-lab-w201724,lsstsqre/jld-lab-w201723,lsstsqre/jld-lab-r130'
            - name: LAB_CONTAINER_DESCS
              value: 'Weekly 2017_26 (Python 3),Weekly 2017_25 (Python 3),Weekly 2017_24 (Python 3),Weekly 2017_23 (Python 3),Release 13.0 (Python 2)'
            - name: LAB_SELECTOR_TITLE
              value: 'LSST Stack Selector'
            # Set these if you want to change them.
            # - name: LAB_MEM_LIMIT
            #   value: '2G'
            # - name: LAB_CPU_LIMIT
            #   value: '1'
            # - name: LAB_MEM_GUARANTEE
            #   value: '0K'
            # - name: LAB_CPU_GUARANTEE
            #   value: '0'
            - name: GITHUB_ORGANIZATION_WHITELIST
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: github_organization_whitelist
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: github_client_id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: github_secret
            - name: OAUTH_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: github_oauth_callback_url
            # This may contain credentials, so it should be a secret
            - name: SESSION_DB_URL
              valueFrom:
                secretKeyRef:
                  name: jld-hub
                  key: session_db_url
          # If you use sqlite, you want this to persist sessions across
          #  jupyterhub restarts.
          volumeMounts:
            - name: jld-fileserver-home
              mountPath: /home
            - name: jld-hub-config
              mountPath: /opt/lsst/software/jupyterhub/config
      volumes:
        - name: jld-fileserver-home
          persistentVolumeClaim:
             claimName: jld-fileserver-home
        - name: jld-hub-config
          configMap:
            name: jld-hub-config
            #  Create with `kubectl create configmap jld-hub-config \
            #   --from-file=config/jld-hub-cfg.py`
            items:
            - key: jld-hub-cfg.py
              path: jupyterhub_config.py
