apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
spec:
  template:
    metadata:
      labels:
        name: filebeat
    spec:
      containers:
        - name: filebeat
          imagePullPolicy: "Always"
          image: "lsstsqre/k8s-filebeat"
          env:
            - name: DEBUG
              value: 'true'
            - name: SHIPPER_NAME
              value: jupyterlabahdemo
            - name: LOGSTASH_HOST
              value: logstashrmq
            - name: LOGSTASH_PORT
              value: '5044'
          volumeMounts:
          - mountPath: /containerlogs
            name: varlibcont
            readOnly: true
          - mountPath: /tls
            name: tls
            readOnly: true
      volumes:
      - name: varlibcont
        hostPath:
          path: /var/lib/docker/containers
      - name: tls
        secret:
          secretName: filebeat
          items:
          - key: ca.crt
            path: ca.crt
          - key: beats.crt
            path: beats.crt
          - key: beats.key
            path: beats.key
